### PR TITLE
Handle an edge case where BVV is passed an empty string (bytes)

### PR DESCRIPTION
**Pull request by iamahuman**
Yes, those edge cases do happen!

### CODE REVIEW

**Comment by rhelmot** [comment]
Can you describe these edge cases? We see a lot of bugs that start with "there's the zero-length string BVV exception being thrown" and end with "there's a bug in the memory model or something that's messing stuff up", so this might obscure some bugs that come up later.

**Comment by iamahuman** [comment]
@rhelmot Actually, I thought passing zero-length string would be perfectly logical despite sounding absurd (you can write zero-length BV into memory which is supposed to do nothing). If it is ever passed an empty string by a bug I think it would probably be an error handling issue (generating empty string rather than throwing an exception). Yes, this certainly would obscure some bugs if it's that case..

**Comment by ltfish** [comment]
> Actually, I thought passing zero-length string would be perfectly logical despite sounding absurd (you can write zero-length BV into memory which is supposed to do nothing).

Thanks for the idea. We discussed about it, and now we have an internal PR that adds support of 0-length BitVectors. Only `Concat` and `Extract` are allowed on 0-length BVs. Arithmetic operations on 0-length BVs are not allowed, because a) the operation does not make sense, and b) we do not mask real mistakes/bugs caused by 0-length BVs.

The internal PR will be merged in after code reviewing, and we'll have to discard this PR than. Sorry :-(

**Comment by ltfish** [comment]
The latest claripy adds a very limited support to 0-length BVVs. Please see this commit: https://github.com/angr/claripy/commit/e17993b774ebcb89422787b560085f5ec5b3a486

I'm closing this PR for now. Thank you again for pointing out this issue.

**Comment by iamahuman** [comment]
Maybe I was aware of edge cases of BVV being made as empty, but not of BVV being used as empty :P

**Pull request closed without merging**
