### PR TITLE
Only edit signal handling in main thread

### PR DESCRIPTION
**Pull request by zwimer**

### CODE REVIEW

**Review by rhelmot — CHANGES_REQUESTED** [review]
I believe this will not work - old_handler must be initialized to _something_, and this will leave it undefined if claripy is imported in a non-main thread.

**Comment by zwimer** [comment]
@rhelmot Correct me if I'm wrong, but `old_handler` should only ever be used in the signal handler after defined, which should only be invoked in the main thread.

**Comment by rhelmot** [comment]
Oops! Yes, that is correct.

**Comment by zwimer** [comment]
I can revert the last commit. I believe it might just add a few cycles to import via the syscall; but it doesn't harm anything. Lmk which you prefer

**Review by rhelmot — APPROVED** [review]

**Comment by rhelmot** [comment]
I don't see how either version will cause problems now, but I approve regardless.

**Pull request merged**
