### PR TITLE
_extract_simplifier: Directly generate flattened AST when possible.

### PR DESCRIPTION
**Pull request by ltfish**

### CODE REVIEW

**Comment by zardus** [comment]
I'm rerunning colorguard, as it failed on the PR test. Might be an intermittent failure, but colorguard and rex are very good at catching simplification problems.

Can you run the rex and tracer testcases on gitlab?

**Comment by ltfish** [comment]
> Can you run the rex and tracer testcases on gitlab?

Do we have angr CI back in the lab?

**Comment by ltfish** [comment]
The colorguard test case failure was obviously a glitch :-)

**Comment by ltfish** [comment]
Ping @zardus

**Comment by zardus** [comment]
I very much didn't forget :-). I don't want to merge this in before we get the rex testcases running -- @salls is almost done with that, so we should be able to merge with confidence soon.

**Comment by rhelmot** [comment]
I think this one is worth reviving.

**Pull request merged**
