### PR TITLE
Add bitvector function docstrings

### PR DESCRIPTION
**Pull request by saullocarvalho**

### CODE REVIEW

**Comment by rhelmot** [comment]
Do we actually want to document things like these @zardus @ltfish ? these seem like internal functions, just implementations of AST operations which are defined elsewhere. at the very least I would note that these are all designed to operate on backend objects for the concrete backend (i.e. BVV objects (NOT bitvectory-typed ASTs) for integers and python bools for booleans.

**Comment by zardus** [comment]
It's probably unnecessary for these, but it doesn't hurt.

**Comment by rhelmot** [comment]
I would like the listed changes made, then. Then I'll hit merge.

**Comment by saullocarvalho** [comment]
I've used @zardus's list as reference and I've looked through `dir(claripy)` to see what still is undocumented.

The functions to which I've added docstrings at this PR are:
************* Module claripy.bv
- bv.py:257 - BitVecVal
- bv.py:260 - ZeroExt
- bv.py:263 - SignExt
- bv.py:266 - Extract
- bv.py:269 - Concat
- bv.py:278 - RotateRight
- bv.py:281 - RotateLeft
- bv.py:284 - Reverse
- bv.py:303 - ULT
- bv.py:308 - UGT
- bv.py:313 - ULE
- bv.py:318 - UGE
- bv.py:323 - SLT
- bv.py:328 - SGT
- bv.py:333 - SLE
- bv.py:338 - SGE
- bv.py:346 - BoolV
- bv.py:349 - And
- bv.py:352 - Or
- bv.py:355 - Not
- bv.py:362 - If
- bv.py:369 - LShR

**Comment by zwimer** [comment]
I'm exceedingly delighted to see PRs improving documentation; even of internal methods.

**Comment by zwimer** [comment]
@rhelmot If the merge conflicts are solved is there anything else holding this back? I can resolve them in a bit if so assuming this PR allows edits from maintainers.

**Comment by rhelmot** [comment]
> I would note that these are all designed to operate on backend objects for the concrete backend (i.e. BVV objects (NOT bitvectory-typed ASTs)

**Comment by zwimer** [comment]
I misunderstood what you meant there; thought you just were stating that rather than asking that be added to the PR. I'll update this PR in a bit if edits are allowed.

**Pull request closed without merging**
