### PR TITLE
Add check for unicode string value in BVV

### PR DESCRIPTION
**Pull request by ekilmer**
ref: #32

### CODE REVIEW

**Comment by ltfish** [comment]
Does that pass linting? I would suggest `isinstance()` instead of `type()` as a general rule.

**Comment by ekilmer** [comment]
Ah. I was also wondering that. It does pass linting, but I agree with you on `isinstance()` instead of `type()`. I didn't know if you wanted consistency or not. I can change it if you'd like.

**Comment by zardus** [comment]
IIRC, I originally had `type()` in there either for speed reasons.

**Comment by ltfish** [comment]
Here are the testing results from CPython 2.7.13.

```
$ python -m timeit -c "isinstance('abc', str)"
10000000 loops, best of 3: 0.0683 usec per loop
$ python -m timeit -c "type('abc') is str"
10000000 loops, best of 3: 0.0681 usec per loop
$ python -m timeit -c "isinstance(1, str)"
10000000 loops, best of 3: 0.139 usec per loop
$ python -m timeit -c "type(1) is str"
10000000 loops, best of 3: 0.0679 usec per loop
```

So it's much slower for `isinstance()` to fail a type match on an object. This is probably because `int`s have `Number` as their base class. Let's stick to `type()` then.

Also, now we are calling `type(value)` three types. It's better to assign it to a temporary variable and then reuse that variable later.

**Pull request merged**
