### PR TITLE
Some docstrings for claripy

### PR DESCRIPTION
**Pull request by jarsp**
I wrote some docstrings for claripy while I was reading the source. I kind of skipped over some of the frontend/backend stuff though, so there's still a fair number left.

### CODE REVIEW

**Comment by zardus** [comment]
Thanks! This merge will be tricky, because we need to avoid conflicts with the `feat/filters` branch. @pcgrosen, is that branch fully up-to-date?

**Comment by pcgrosen** [comment]
@zardus `feat/filters` should be up to date now!

**Comment by zardus** [comment]
@pcgrosen, since I slacked on this again, would you mind terribly if I dumped the rebasing of this on feat/filters on you? I'm obviously a bottleneck right now :-)

**Comment by pcgrosen** [comment]
@zardus Working on this right now! Tons of conflicts, but I'll try to get it done by Thursday.

**Comment by pcgrosen** [comment]
@zardus @jarsp This has been "merged" into `feat/filters`. Doing an actual merge/rebase was going to be  very messy, so I manually added the docstrings in [918573b](https://github.com/angr/claripy/commit/918573b51fd3e04f043f52ba5971dc3ca2ddf7d4) Thanks again for the contribution!

**Pull request closed without merging**
