### PR TITLE
Add path to fix Mac installation

### PR DESCRIPTION
**Pull request by tiffanyb**

### CODE REVIEW

**Comment by ltfish** [comment]
Looks good to me.

@zardus to add a bit context: by default our `angr-only-z3-custom` will be installed to a weird directory on OS X, which is specified by `sys.prefix`. Any comment?

**Comment by zardus** [comment]
Fine by me. Do you think it'll fix https://github.com/angr/pyvex/issues/33?

**Comment by ltfish** [comment]
@zardus Yeah I think so.

@tiffanyb I think line 40 should be changed to the following. What do you think?

```
       if not '.so' in z3_path and not '.dll' in z3_path and not '.dylib' in z3_path: 
```

**Comment by H4rryp0tt3r** [comment]
I made changes to the files, now I'm getting a different error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/Library/Python/2.7/site-packages/angr/project.py", line 11, in <module>
    import simuvex
  File "/Library/Python/2.7/site-packages/simuvex/__init__.py", line 9, in <module>
    from .s_state import SimState
  File "/Library/Python/2.7/site-packages/simuvex/s_state.py", line 11, in <module>
    import claripy
  File "/Library/Python/2.7/site-packages/claripy/__init__.py", line 17, in <module>
    from . import backends as _backends_module
  File "/Library/Python/2.7/site-packages/claripy/backends/__init__.py", line 1, in <module>
    from .backend_z3 import BackendZ3
  File "/Library/Python/2.7/site-packages/claripy/backends/backend_z3.py", line 43, in <module>
    z3.init(z3_path)
AttributeError: 'module' object has no attribute 'init'

**Comment by ltfish** [comment]
@H4rryp0tt3r I'm not sure what's going on there, but do you want to try recompiling and reinstalling the z3 by the following command: `pip install -I --no-use-wheel angr-only-z3-custom`?

**Comment by tiffanyb** [comment]
@ltfish about line 40: sure, thanks for pointing out
@H4rryp0tt3r Do you have any problem before changing? I want to make sure if this is caused by the change.

**Comment by zardus** [comment]
So now this is all ready?

**Comment by ltfish** [comment]
I think so. I'll merge it in now.

**Comment by ltfish** [comment]
@tiffanyb Thank you :-)

**Comment by tiffanyb** [comment]
Sure. BTW, you can close the issue angr/pyvex 33.

@tiffanyb <https://github.com/tiffanyb> Thank you :-)

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/angr/claripy/pull/4#issuecomment-198651146>

**Pull request merged**
