### PR TITLE
Fix Z3 StringV abstraction

### PR DESCRIPTION
**Pull request by zwimer**
Fixes: https://github.com/angr/claripy/issues/298

### CODE REVIEW

**Comment by zwimer** [comment]
Requesting review from @ltfish because `git blame` shows him as the last to touch this code.

**Comment by zwimer** [comment]
@ltfish I think the new python API handles the encoding issues (though there is a bug: https://github.com/Z3Prover/z3/issues/6442 )

**Review by rhelmot — APPROVED** [review]
I'm putting my stamp of approval on this, but I really don't understand what's going on. I am fairly sure the bus factor for the string stuff is zero.

**Comment by zwimer** [comment]
Ping @ltfish

**Comment by zwimer** [comment]
I'm going to merge this since it was approved; if it causes issues we can always revert.

**Pull request merged**
