### PR TITLE
fix zeroext_comparing_against_simplifier

### PR DESCRIPTION
**Pull request by xxr0ss**
fix https://github.com/angr/angr/issues/4754

link: https://github.com/angr/binaries/pull/126

### CODE REVIEW

**Comment by xxr0ss** [comment]
I think the "Concat" part should apply the same fix, but if I do so, `angr/tests/sim/exec_func/test_syscall_result.py` would fail for arch `x86_64`

```diff py
diff --git a/claripy/simplifications.py b/claripy/simplifications.py
index 9de98806..0017c147 100644
--- a/claripy/simplifications.py
+++ b/claripy/simplifications.py
@@ -1155,8 +1155,11 @@
            if (
                a.op == "Concat" and len(a.args) == 2 and a.args[0].op == "BVV" and a.args[0].args[0] == 0
            ):  # make sure high bits of a are zeros
                a_zero_bits = a.args[0].args[1]
                b_highbits = b[b.size() - 1 : b.size() - a_zero_bits]
                if (b_highbits == 0).is_true():
                    # we can get rid of Concat
                    return op(a.args[1], b[b.size() - a_zero_bits - 1 : 0])
                if (b_highbits == 0).is_false():
                 if (b_highbits == 0).is_false():
-                    # unsat
-                    return claripy.false if op is operator.__eq__ else claripy.true
+                    if op is operator.__eq__:
+                        return claripy.false
+                    if op is operator.__ne__:
+                        return claripy.true
+                    return claripy.false

         return None
```

**Comment by twizmwazin** [comment]
Looks like there is a failing test case still. Could I also get you to add a test case or two to prevent regressions?

**Comment by xxr0ss** [comment]
> Looks like there is a failing test case still. Could I also get you to add a test case or two to prevent regressions?

Tests added. the failing test case is related to https://github.com/angr/binaries/issues/124, I'm not sure how the currently existing glibc binaries were added, could you the angr team can help update the `libc.so`?

**Comment by twizmwazin** [comment]
Reran the CI with your new binary, seems like the newer libc is causing other tests to fail. You might want to consider adding the libc rather than replacing the current one.

**Comment by xxr0ss** [comment]
@twizmwazin thanks for your advice, modifications have been made to [`angr/binaries`](https://github.com/angr/binaries/pull/126) and [`angr/angr`](https://github.com/angr/angr/pull/4903)

**Comment by twizmwazin** [comment]
Thanks!

**Pull request merged**
