### PR TITLE
Z3: clone the solver instead of adding constraints to a fresh instance

### PR DESCRIPTION
**Pull request by CanCebeci**
This results in increased incrementalism and thus speeds up further queries (See https://github.com/Z3Prover/z3/issues/556). Leads to 10-25% reduction in execution time in my private benchmarks.

### CODE REVIEW

**Comment by rhelmot** [comment]
Can you do some tests to check the performance impact on our existing angr/tests/perf tests (should be minimal) and also on some public solving-heavy tests - I would do test_tracer and then the wyvern example in angr-doc

**Comment by rhelmot** [comment]
Also, if you have a workload which you feel like isn't represented by any of our standard perf tests, you can write one and submit a PR and we'll run it every night to check for regressions!

**Comment by CanCebeci** [comment]
I'd gladly do some more performance benchmarks. But before that could you help me understand why that one test fails? I don't understands what it is doing.

**Comment by rhelmot** [comment]
It's a spurious failure. I've run it again and it's passed!

**Comment by ltfish** [comment]
OMG for five years we did not see the second comment in the original Z3 issue about `translate()`...

**Comment by rhelmot** [comment]
I'm going to merge this and fix any problems that come of it :)

**Pull request merged**
