### PR TITLE
Load correct library depending on OS

### PR DESCRIPTION
**Pull request by cao**

### CODE REVIEW

**Comment by rhelmot** [comment]
Could you somehow update this to have a check for `sys.platform == "windows"`?

**Comment by cao** [comment]
I don't have a Windows installation where I can test it, hence I cannot easily add it.

**Comment by cao** [comment]
Windows VM setup and Windows support added :-)

Claripy is untested but should work (same way has been added to Z3, which was tested and working).

**Comment by zardus** [comment]
Thanks!

**Pull request merged**
