### PR TITLE
propagate anno

### PR DESCRIPTION
**Pull request by wuruoyu**
It is to solve this: https://github.com/angr/angr/issues/2867#issuecomment-901521771. You can check the issue for more details.

### CODE REVIEW

**Comment by rhelmot** [comment]
I worry that this will cause problems because of hash consing. Annotations are supposed to be part of the AST's identity, but mutating an already-built AST will mutate other references to the same instance. What you want is probably to use the .annotate() function.

**Comment by wuruoyu** [comment]
Thanks for your quick reply. 
Are you suggesting, instead of ```s.annotations = e.annotations```, the following is preferred? 

```
for  anno in e.annotations:
  s.annotate(anno)
```

**Comment by rhelmot** [comment]
Not quite - the point is that once an AST has exited `Base.__new__`, it should never have its identity mutated, so as a result `s.annotate()` is a pure function. You want `s = s.annotate(anno)`.

**Comment by wuruoyu** [comment]
Thanks for your explanation! I have updated the PR accordingly.

**Comment by rhelmot** [comment]
You actually want `s.annotate(*e.annotations)`. The function takes variadic args.

**Pull request merged**
