### PR TITLE
Edit test_solver so tests actually run

### PR DESCRIPTION
**Pull request by zwimer**
Fixes: https://github.com/angr/claripy/issues/303

### CODE REVIEW

**Comment by zwimer** [comment]
Also leads to running more tests in `__main__` that were previously not run.

**Comment by twizmwazin** [comment]
Why was this merged with a failing lint? @zwimer can you make a follow up that addresses the lint issues?

**Comment by zwimer** [comment]
@twizmwazin Most all of the issues in the lint are either `Method could be a function (no-self-use)`, though unittest examples all take in `self` so assuming we want to follow that convention I'd ignore each issue there. The other big issue is `Instance of 'Base' has no 'solver' member (no-member)`; but that is intentional, it if something tries to run these without defining `solver` in a subclass it should error, it shouldn't start executing as it might if we had `solver=None`; so I'd also ignore that warning.

If I add a pylint disable these to the top of the file, will that disable them for the entire file? Otherwise we'd just have to spam disable warnings everywhere which I am ok with not-doing on a test case file

**Comment by twizmwazin** [comment]
I agree with no-self-use and docstrings being superfluous here, but wrong-import-order, no-member, duplicate entry in set all seem like things that should be resolved. no-member could be better solved with an abstract class and still achieve the behavior you want. Adding a pylint ignore at the top of a file or class applies to the entire file/class.

**Pull request merged**
