### PR TITLE
Remove all `__div__` uses from claripy

### PR DESCRIPTION
**Pull request by zwimer**
`__div__` is python2. We now have `__floordiv__` and `__truediv__`. Claripy already had `__div__` simply aliasing one of the two in all use cases; these have been removed since we no longer support python2.

Related angr PR: merged

### CODE REVIEW

**Comment by zwimer** [comment]
This PR seems to be failing tests because some angr tests specifically test `__div__`. Since angr is also python3 I will make a PR in angr to remove / replace these test cases with `__truediv__`.

**Comment by zwimer** [comment]
Angr PR: https://github.com/angr/angr/pull/2540

**Comment by zwimer** [comment]
This is a re-run of the CI using the new angr branch:
https://dev.azure.com/angr/claripy/_build/results?buildId=6183&view=results

**Comment by rhelmot** [comment]
so the only thing wrong with the CI you linked is that lint is failing, which means it's time for you to partake in a very important angr maintenance ritual - linting code that you didn't touch because it's in a file you removed lines from which caused the score ratio to regress. It's gotta happen, unfortunately.

**Comment by rhelmot** [comment]
It looks like the rest of your PRs also have this problem - since you will probably introduce merge conflicts if you lint all the overlapping files separately, I give you my blessing to manually merge all your remaining PRs into your local master branch, then fix lint on all the affected files, and then push directly to master.

**Comment by zwimer** [comment]
All lint errors are fixed except for ones of the form:
```
claripy/ast/bv.py:88:11: E1101: Instance of 'NotImplemented' has no 'size' member (no-member)
```
Which seem like either proper errors, or the linter being too dumb to recognize things.

**Comment by twizmwazin** [comment]
https://dev.azure.com/angr/claripy/_build/results?buildId=6538&view=results

**Comment by rhelmot** [comment]
Your annotation is malformed: you want `r: BV` instead of `BV: r`. Do you know how to run pylint locally?

**Review by rhelmot — APPROVED** [review]

**Pull request merged**
