### PR TITLE
Make the code more python3-compatible

### PR DESCRIPTION
**Pull request by palkeo**
It's a long way from being compatible with python3, but it should help.

Clean up print statements, and references to long.
Reorder imports, too.

It contains multiple commits, because I have no idea how to use git properly. But the diff is the right one.

### CODE REVIEW

**Comment by zardus** [comment]
@pcgrosen or @Lukas-Dresel, could you guys rebase `feat/filters` on top of this (or a squashed version of this) so that we can merge it in?

**Comment by rhelmot** [comment]
Does this cause any performance issues? We use `type` instead of `isinstance` for speed reasons.

**Comment by ltfish** [comment]
> Does this cause any performance issues?

We should provide some test cases just for benchmarking.

**Comment by rhelmot** [comment]
From discussion in slack: the `_get_hashables` method seems to be totally unused, so its performance doesn't really matter!

**Comment by rhelmot** [comment]
Almost there - you just have a bunch of lint regressions: https://travis-ci.org/angr/claripy/jobs/270662171#L1391

We use pylint with the pylintrc file found in the angr-dev repo to ensure that our code quality is tolerable :)

**Comment by rhelmot** [comment]
Oh hm - the vast majority of those lint failures are "superfluous parens", but we need those for python 3... I will disable that message in the pylintrc.

**Comment by palkeo** [comment]
I merged, and fixed some lint errors. Travis passes, AppVeyor fails, but I was always the case if I look at the history

**Comment by ltfish** [comment]
Thanks! Appveyor currently does not work. I believe you've fixed everything!

**Comment by rhelmot** [comment]
Awesome, thank you!

**Pull request merged**
