### PR TITLE
Added simplifier for the Reverse(Extract(Reverse([...]))) pattern

### PR DESCRIPTION
**Pull request by axt**
Related issue: https://github.com/angr/claripy/issues/23

### CODE REVIEW

**Comment by zardus** [comment]
Regarding testing this change -- these simplifications are applied automatically by claripy, so the simplifiers just need to make the `Reverse(Extract(Reverse)))` AST, then check that it's magically simplified. Would you mind putting that into `test_expression.py`?

**Comment by axt** [comment]
I've tried this, but it causes assertion error:
```
def test_reverse_extract():
    a = claripy.BVS("a", 32)
    b = claripy.Reverse(claripy.Extract(31,16,claripy.Reverse(a)))
    assert b is a[15:0]
```

Although I can check the patch working on this code snippet:
```
    """
	0x0:	push	ebp
	0x1:	mov	ebp, esp
	0x3:	movsx	esi, word ptr [ebp + 8]
	0x7:	cmp	si, 0x7f
	0xb:	jg	0x24
    """
    code = "\x55\x89\xe5\x0f\xbf\x75\x08\x66\x83\xfe\x7f\x7f\x17"
    proj = angr.Project(io.BytesIO(code), load_options={'main_opts': {'custom_arch':'x86'}})
    state = proj.factory.blank_state(addr=0x0, add_options={o.AVOID_MULTIVALUED_READS, o.AVOID_MULTIVALUED_WRITES, o.USE_SIMPLIFIED_CCALLS})
    state.memory.store(state.regs.esp+ 4, claripy.BVS('arg0', proj.arch.bits), endness=proj.arch.memory_endness, inspect=False)					# ebp+0x8

    simrun  = proj.factory.sim_run(state)
    print simrun.default_exit_guard.args[0]
```

Any ideas?

**Comment by zardus** [comment]
This got completely dropped on my end, unfortunately... @axt, do you have some time to rebase this, then we can look into failures?

**Comment by axt** [comment]
@zardus sry, just saw your message. in a hurry now, but will rebase it tomorrow!

**Pull request closed without merging**
